#!/bin/sh

DEVICE="HBW-Sen-SC-12-DR"
DEVICE_IMG=hbw-sen-sc-12.png
DEVICE_THUMB=hbw-sen-sc-12_thumb.png
FIRMWARE_FILE=/firmware/hs485types/hbw_sen_sc_12_dr.xml

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile


rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB

### Edit webui.js ###